"""upgrade table comments

Revision ID: 5000c323c2d9
Revises: 54d7571f4985
Create Date: 2023-04-15 23:26:11.428765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5000c323c2d9'
down_revision = '54d7571f4985'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'created')
    # ### end Alembic commands ###
